SOAL 1a

In [23]:
import numpy as np

In [83]:
newarray = []
start = int(input("Isi nomor start: "))
end = int(input("Isi nomor end: "))
newarray = np.arange(start, end)
print(newarray)
print(type(newarray))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
<class 'numpy.ndarray'>

In [80]:
# KALAU MAU MULTIPEL GIMANA?
anothernewarray = list(map(int, input("Isi nomor untuk didalam array(dengan spasi setiap nomor baru): ").split()))
anothernewarray = np.array(anothernewarray)
print(anothernewarray)

[]

SOAL 1b

In [85]:
#UNTUK 27 isi nya array aja
newarray2d = newarray.reshape(3,9)
print(f"2D = {newarray2d}")

newarray3d = newarray.reshape(3,3,3)
print(f"3D = {newarray3d}")

2D = [[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
3D = [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

In [62]:
import math

In [77]:
#KALAU MAU  JADI 2D OTOMATIS GIMANA?
lennyaArray = len(newarray)
# row bisa di square root tapi kalau angkanya kayak 5 atau 7 gimana?
row2d = int(math.sqrt(lennyaArray))
while lennyaArray % row2d != 0:
    row2d -= 1
# Cari dulu columnya berapa
column2d = lennyaArray // row2d
#reshape
anothernewarray2d = newarray.reshape(row2d, column2d)
anothernewarray2d.shape

(3, 3)

In [ ]:
#KALAU MAU JADI 3D OTOMATIS GIMANA?
lennyaArray = len(newarray)
row3d = int(lennyaArray**(1/3))
while lennyaArray % row3d != 0:
    row3d -= 1
#SISA 2 SHAPE
sisa_isi = int(math.sqrt(lennyaArray // row3d))
while sisa_isi % sisa_isi != 0:
    sisa_isi -= 1
#SISA 1 SHAPE
column3d = (lennyaArray//row3d) // sisa_isi
anothernewarray3d = newarray.reshape(row3d, sisa_isi, column3d)
anothernewarray3d.shape

(1, 3, 3)

SOAL 2A

In [94]:
#RANDOM
n = int(input("Angka untuk 1D: "))
t = int(input("Batasan random: "))
a= np.random.rand(1,n,t)
print(a)
#RANDOMINT (JAWABANNYA YG INI UNTUK RANDOM INTEGER)
b = np.random.randint(1,n,t)
print(b)
#RANDOMN
c = np.random.randn(1,n)
print(c)

[[[0.84946919 0.29235366 0.84376922 0.8137511  0.37766612 0.38587627
   0.21099848 0.81661308 0.93557791 0.46755215]
  [0.78761355 0.33159835 0.74652373 0.75968146 0.28959668 0.31616731
   0.06397673 0.31817992 0.02372032 0.84756212]
  [0.30727383 0.14777216 0.23113611 0.13644832 0.99498535 0.10812409
   0.62590362 0.5113683  0.70248088 0.56437243]
  [0.1166479  0.87223886 0.72034792 0.58850194 0.87912324 0.11809981
   0.21806117 0.4483886  0.33486029 0.37897172]
  [0.45472475 0.7342873  0.69942495 0.7975924  0.60485338 0.49881598
   0.01860545 0.16269344 0.05961402 0.43881299]]]
[3 2 3 1 2 2 3 2 4 4]
[[ 0.01942438 -0.10803122 -1.43457378 -0.43576402  0.55145181]]

SOAL 2C

In [107]:
# JADIIN 2D
rowskrng = int(len(b) // 2)
while len(b) % rowskrng  != 0:
    rowskrng -= 1
columnskrng = int(len(b) / rowskrng)
b = b.reshape(rowskrng, columnskrng)

SOAL 2D

In [ ]:
# BALIKAN SEMUA URUTAN DATANYA
print(b)
b = b[:,::-1] #ROW [:], Column [::-1]
print(f"NewB = {b}")

[[3 2]
 [3 1]
 [2 2]
 [3 2]
 [4 4]]
NewB = [[2 3]
 [1 3]
 [2 2]
 [2 3]
 [4 4]]

SOAL 3

In [231]:
thirdarray = np.eye(10)

#3b
thirdarray[:] = 4
thirdarray[1:9, 1:9] = 0
print(thirdarray)

#Gimana kalau mulai dari 0 duluan?
thirdarray[:] = 0
thirdarray[0] = 4
thirdarray[-1] = 4
thirdarray[1:9, 0] = 4
thirdarray[1:9, -1] = 4
print(thirdarray)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]
[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]

SOAL 4

In [156]:
import pandas as pd

In [161]:
index1 = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
data1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
pd.Series(data = data1, index = index1)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

SOAL 5

In [219]:
# CARA 1 PYTHON
newSeries = pd.Series(data = np.random.randint(1,5,100))
number1 = 0
number2 = 0
number3 = 0
number4 = 0
for i in newSeries:
    if i == 1:
        number1 += 1
    elif i == 2:
        number2 += 1
    elif i == 3:
        number3 += 1
    else:
        number4 += 1
list1 = [number1, number2, number3, number4]
print(f'''1 = {number1}
2 = {number2}
3 = {number3}
4 = {number4}''')
print(list1)

# Cari 2 number dengan frekuensi tertinggi
# CARA ini eror kalau index 0 dan index 1 highest frequency (mungkin lebih bagus di remove, masukin ke list lain)
firsthighest = max(list1)
firstvalue = list1.index(firsthighest) + 1

copylist1 = list1.copy()
copylist1.remove(firsthighest)
secondhighest = max(copylist1)
secondvalue = list1.index(secondhighest) + 1

print(f"The two highest are frequency {firsthighest} and {secondhighest} with value {firstvalue} and {secondvalue}")

1 = 23
2 = 30
3 = 21
4 = 26
[23, 30, 21, 26]
The two highest are frequency 30 and 26 with value 2 and 4

In [ ]:
#CARA 3 PYTHON + SORT
twohighest = sorted(
    newSeries.value_counts().items(), key=lambda x: x[1], reverse=True)[:2]

for value, frequency in twohighest:
    print(f"The two highest are {frequency} with value {value}")

The two highest are 30 with value 2
The two highest are 26 with value 4

In [232]:
#CARA 3 PYTHON + DICT
# Cari 2 number dengan frekuensi tertinggi
dict1 = {1: number1, 2: number2, 3:number3, 4:number4}
highestoftwo = sorted(dict1.items(), key=lambda x: x[1], reverse=True)[:2]
print(f"""The two highest are frequency {highestoftwo[0][1]} and {highestoftwo[1][1]}
    with values {highestoftwo[0][0]} and {highestoftwo[1][0]}""")

The two highest are frequency 30 and 26
    with values 2 and 4

In [ ]:
# CARA 4 NUMPY AND PANDAS
newSeries = pd.Series(data = np.random.randint(1,5,100))
x, y = np.unique(newSeries, return_counts=True)

newCount = pd.DataFrame(data = {"value": x, "frequency": y})
print(newCount)

highesttwo = newCount.sort_values(by="frequency", ascending=False).head(2)
highesttwo

   value  frequency
0      1         30
1      2         23
2      3         25
3      4         22

   value  frequency
0      1         30
2      3         25

SOAL 6

In [1]:
import seaborn as sns
mpg = sns.load_dataset('mpg')

In [2]:
#6b
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [3]:
#6c
mpg.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [10]:
#6d
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='str')

In [16]:
#6e
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

SOAL 7

In [17]:
#7a
import seaborn as sns
mpg = sns.load_dataset('mpg')

In [29]:
#7b
mpg[mpg['horsepower'].isna()]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
126,21.0,6,200.0,NaN,2875,17.0,74,usa,ford maverick
330,40.9,4,85.0,NaN,1835,17.3,80,europe,renault lecar deluxe
336,23.6,4,140.0,NaN,2905,14.3,80,usa,ford mustang cobra
354,34.5,4,100.0,NaN,2320,15.8,81,europe,renault 18i
374,23.0,4,151.0,NaN,3035,20.5,82,usa,amc concord dl

In [34]:
#7c
mpg[mpg['horsepower'].isna()].index

Index([32, 126, 330, 336, 354, 374], dtype='int64')

SOAL 8

In [1]:
import seaborn as sns
mpg = sns.load_dataset('mpg')

In [11]:
mpg.groupby('origin')[['horsepower']].mean()

        horsepower
origin
europe   80.558824
japan    79.835443
usa     119.048980

SOAL 9

In [12]:
import seaborn as sns
mpg = sns.load_dataset('mpg')

In [28]:
#9b & C
mpg['horse_origin'] = np.where(
    mpg['horsepower'] < 105, 'lower ' + mpg['origin'], 'upper ' + mpg['origin']  
)
mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name,horse_origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu,upper usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320,upper usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite,upper usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst,upper usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino,upper usa
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl,lower usa
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup,lower europe
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage,lower usa
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger,lower usa
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10,lower usa

SOAL 10

In [ ]:
import seaborn as sns
mpg = sns.load_dataset('mpg')

In [34]:
#10b
weightgroup = mpg.groupby('origin')[['weight']].describe()
weightgroup

       weight                                                             \
        count         mean         std     min      25%     50%      75%
origin
europe   70.0  2423.300000  490.043191  1825.0  2067.25  2240.0  2769.75
japan    79.0  2221.227848  320.497248  1613.0  1985.00  2155.0  2412.50
usa     249.0  3361.931727  794.792506  1800.0  2720.00  3365.0  4054.00


           max
origin
europe  3820.0
japan   2930.0
usa     5140.0

In [35]:
#10c
weightgroup.reset_index()

   origin weight                                                             \
           count         mean         std     min      25%     50%      75%
0  europe   70.0  2423.300000  490.043191  1825.0  2067.25  2240.0  2769.75
1   japan   79.0  2221.227848  320.497248  1613.0  1985.00  2155.0  2412.50
2     usa  249.0  3361.931727  794.792506  1800.0  2720.00  3365.0  4054.00


      max
0  3820.0
1  2930.0
2  5140.0